id: Phishing v2 Test - Attachment - Real
fromversion: 6.0
version: -1
name: Phishing v2 Test - Attachment - Real
description: ""
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 34d9eb3b-72f2-4667-8943-fac0f913d5af
    type: start
    task:
      id: 34d9eb3b-72f2-4667-8943-fac0f913d5af
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": -140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: c0cdc434-d0f7-4e51-8e85-1900831d5591
    type: title
    task:
      id: c0cdc434-d0f7-4e51-8e85-1900831d5591
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 855
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: de4e3829-056d-465c-824f-73f0c23b11e7
    type: regular
    task:
      id: de4e3829-056d-465c-824f-73f0c23b11e7
      version: -1
      name: Close manual review in the new incident
      description: ""
      scriptName: ScheduleCommand
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      command:
        simple: '!CompleteManualTask id=${CreatedIncidentID}'
      cron:
        simple: '*/1 * * * *'
      endDate: {}
      times:
        simple: "20"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 2e40435f-f6f8-4489-8ab1-7cdd582bbeaa
    type: regular
    task:
      id: 2e40435f-f6f8-4489-8ab1-7cdd582bbeaa
      version: -1
      name: Delete Context
      description: ""
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 5
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 16aee5dd-90b3-4850-81d9-1f79dbb32499
    type: regular
    task:
      id: 16aee5dd-90b3-4850-81d9-1f79dbb32499
      version: -1
      name: Download EML file
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
      - "22"
    scriptarguments:
      body: {}
      filename:
        simple: attachment.eml
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/attachment_malicious_url.eml
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 505
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: f6f8a203-6c69-473b-8271-ddff24d14b1c
    type: regular
    task:
      id: f6f8a203-6c69-473b-8271-ddff24d14b1c
      version: -1
      name: Create malicious URL indicator
      description: commands.local.cmd.new.indicator
      script: Builtin|||createNewIndicator
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      accounttype: {}
      actor: {}
      admincountry: {}
      adminemail: {}
      adminname: {}
      adminphone: {}
      asn: {}
      associatedfilenames: {}
      associations: {}
      biosversion: {}
      campaign: {}
      creationdate: {}
      customFields: {}
      cvedescription: {}
      cvemodified: {}
      cvss: {}
      description: {}
      detectionengines: {}
      devicemodel: {}
      dhcpserver: {}
      displayname: {}
      dns: {}
      domainname: {}
      domainstatus: {}
      emailaddress: {}
      entryid: {}
      expirationdate: {}
      fileextension: {}
      filetype: {}
      firstseenbysource: {}
      geocountry: {}
      geolocation: {}
      groups: {}
      hostname: {}
      imphash: {}
      indicatoridentification: {}
      internal: {}
      ipaddress: {}
      lastseenbysource: {}
      macaddress: {}
      malwarefamily: {}
      md5: {}
      memory: {}
      merge: {}
      mitreexternalreferences: {}
      name: {}
      namefield: {}
      nameservers: {}
      office365category: {}
      office365expressroute: {}
      office365required: {}
      operatingsystem: {}
      operatingsystemversion: {}
      organization: {}
      organizationalunitou: {}
      osversion: {}
      path: {}
      port: {}
      positivedetections: {}
      processor: {}
      processors: {}
      published: {}
      quarantined: {}
      region: {}
      registrantcountry: {}
      registrantemail: {}
      registrantname: {}
      registrantphone: {}
      registrarabuseemail: {}
      registrarabusephone: {}
      registrarname: {}
      relateToIncident: {}
      relatedIncidents: {}
      reportedby: {}
      reputation:
        simple: Bad
      seenNow: {}
      service: {}
      sha1: {}
      sha256: {}
      sha512: {}
      signatureauthentihash: {}
      signaturecopyright: {}
      signaturedescription: {}
      signaturefileversion: {}
      signatureinternalname: {}
      signed: {}
      size: {}
      source: {}
      sourceTimeStamp: {}
      sourceoriginalseverity: {}
      ssdeep: {}
      subdomains: {}
      tags: {}
      threattypes: {}
      trafficlightprotocol: {}
      type:
        simple: URL
      updateddate: {}
      username: {}
      value:
        simple: http://www.desktop-style.de
    reputationcalc: 1
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "22":
    id: "22"
    taskid: d0358cf6-f74d-4cd0-8c10-652b75bcfd2a
    type: playbook
    task:
      id: d0358cf6-f74d-4cd0-8c10-652b75bcfd2a
      version: -1
      name: Phishing Investigation - Generic v2
      description: |-
        Use this playbook to investigate and remediate a potential phishing incident. The playbook simultaneously engages with the user that triggered the incident, while investigating the incident itself.

        The final remediation tasks are always decided by a human analyst.
      playbookName: Phishing Investigation - Generic v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      AuthenticateEmail:
        simple: "False"
      BlockIndicators:
        simple: "False"
      OnCall:
        simple: "false"
      Role:
        simple: Administrator
      SearchAndDelete:
        simple: "False"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 480,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: 658e41b8-3603-41b7-8872-c39c230a15af
    type: regular
    task:
      id: 658e41b8-3603-41b7-8872-c39c230a15af
      version: -1
      name: Set phishing incident fields
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      accountid: {}
      accountname: {}
      addLabels: {}
      agentid: {}
      app: {}
      appendMultiSelect: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      blockedaction: {}
      bugtraq: {}
      city: {}
      closeNotes: {}
      closeReason: {}
      commandline: {}
      country: {}
      criticalassets: {}
      customFields: {}
      cve: {}
      cvss: {}
      dbotMirrorDirection: {}
      dbotMirrorId: {}
      dbotMirrorInstance: {}
      dbotMirrorTags: {}
      dbotprediction: {}
      dbotpredictionprobability: {}
      dbottextsuggestionhighlighted: {}
      deleteEmptyField: {}
      dest: {}
      desthostname: {}
      destinationhostname: {}
      destinationip: {}
      destinationport: {}
      destntdomain: {}
      destos: {}
      details: {}
      detectionendtime: {}
      detectionid: {}
      detectionupdatetime: {}
      detectionurl: {}
      devicename: {}
      duration: {}
      emailauthenticitycheck: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclassification: {}
      emailclientname: {}
      emailfrom:
        simple: test@demistodev.com
      emailheaders: {}
      emailhtml: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject:
        simple: Hello! This is not the phishing one.
      emailto:
        simple: admin@demistodev.com
      emailtocount: {}
      emailurlclicked: {}
      employeedisplayname: {}
      employeeemail: {}
      employeemanageremail: {}
      eventid: {}
      eventtype: {}
      filehash: {}
      filename: {}
      filepath: {}
      filesize: {}
      firstseen: {}
      helloworldid: {}
      helloworldstatus: {}
      helloworldtype: {}
      hostname: {}
      id: {}
      infectedhosts: {}
      investigationstage: {}
      isolated: {}
      labels:
        simple: '[{"Email/from":"test@demistodev.com"}, {"Email/to": "admin@demistodev.com"}]'
      lastmodifiedby: {}
      lastmodifiedon: {}
      lastseen: {}
      logsource: {}
      macaddress: {}
      maliciousbehavior: {}
      malwarefamily: {}
      name: {}
      occurred: {}
      os: {}
      owner: {}
      parentprocessid: {}
      phase: {}
      phishingsubtype: {}
      pid: {}
      policydeleted: {}
      policydescription: {}
      policydetails: {}
      policyid: {}
      policyrecommendation: {}
      policyremediable: {}
      policyseverity: {}
      policytype: {}
      protocol: {}
      quarantined: {}
      rating: {}
      region: {}
      regionid: {}
      replacePlaybook: {}
      reporteremailaddress: {}
      resourceid: {}
      resourcename: {}
      resourcetype: {}
      riskrating: {}
      riskscore: {}
      roles: {}
      samaccountname: {}
      severity: {}
      signature: {}
      skuname: {}
      skutier: {}
      sla: {}
      slaField: {}
      sourcehostname: {}
      sourceip: {}
      sourceport: {}
      sourceusername: {}
      src: {}
      srchostname: {}
      srcntdomain: {}
      srcos: {}
      srcuser: {}
      subtype: {}
      systems: {}
      tenantname: {}
      terminatedaction: {}
      threatactor: {}
      triggeredsecurityprofile: {}
      type: {}
      urlsslverification: {}
      user: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1060,
        "width": 810,
        "x": 50,
        "y": -140
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: Phishing v2 Test - Attachment
